version: "3"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
  db:
    container_name: my_sql
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - ./.env
